gs_contract_homepage:
    path:     /hello/{name}
    defaults: { _controller: GSUserBundle:Default:index }

gs_contract_index:
    path:     /index
    defaults: { _controller: GSUserBundle:Contract:index }

gs_contract_add:
    path:     /add
    defaults: { _controller: GSUserBundle:Contract:add }

gs_contract_create:
    path:     /create
    defaults: { _controller: GSUserBundle:Contract:create }
    methods: POST
    
gs_contract_edit:
    path:     /edit/{id}
    defaults: { _controller: GSUserBundle:Contract:edit }

gs_contract_update:
    path:     /update/{id}
    defaults: { _controller: GSUserBundle:Contract:update }
    methods: [POST, PUT]

gs_contract_view:
    path:     /view/{id}
    defaults: { _controller: GSUserBundle:Contract:view }

gs_contract_redirect_add:
    path:     /create
    defaults: 
        _controller: GSUserBundle:Contract:add
        path:   /add
        permanent: true

gs_contract_redirect_edit:
    path:     /update/{id}
    defaults: 
        _controller: GSUserBundle:Contract:edit
        path:   /edit/{id}
        permanent: true

gs_contract_searchcontract:
    path:     /searchcontract
    defaults: { _controller: GSUserBundle:Contract:searchcontract }