gs_street_homepage:
    path:     /hello/{name}
    defaults: { _controller: GSUserBundle:Default:index }

gs_street_index:
    path:     /index
    defaults: { _controller: GSUserBundle:Street:index }

gs_street_add:
    path:     /add
    defaults: { _controller: GSUserBundle:Street:add }

gs_street_create:
    path:     /create
    defaults: { _controller: GSUserBundle:Street:create }
    methods: POST
    
gs_street_edit:
    path:     /edit/{id}
    defaults: { _controller: GSUserBundle:Street:edit }

gs_street_update:
    path:     /update/{id}
    defaults: { _controller: GSUserBundle:Street:update }
    methods: [POST, PUT]

gs_street_view:
    path:     /view/{id}
    defaults: { _controller: GSUserBundle:Street:view }

gs_street_delete:
    path:     /delete/{id}
    defaults: { _controller: GSUserBundle:Street:delete }
    methods: [POST, DELETE]

gs_street_redirect_add:
    path:     /create
    defaults: 
        _controller: GSUserBundle:Street:add
        path:   /add
        permanent: true

gs_street_redirect_edit:
    path:     /update/{id}
    defaults: 
        _controller: GSUserBundle:Street:edit
        path:   /edit/{id}
        permanent: true
        
gs_street_searchstreet:
    path:     /searchstreet
    defaults: { _controller: GSUserBundle:Street:searchstreet}
    
gs_street_selectzone:
    path:     /selectzone
    defaults: { _controller: GSUserBundle:Street:selectzone}