gs_user_user:
    resource: "@GSUserBundle/Resources/config/routes/user.yml"
    prefix: /user

# Autentication

gs_user_homepage:
    path:   /
    defaults: { _controller: GSUserBundle:User:home }

gs_user_login:
    path:   /login
    defaults: { _controller: GSUserBundle:Security:login }

gs_user_login_check:
    path:   /login_check
    defaults: { _controller: GSUserBundle:User:loginCheck }
    
gs_user_logout:
    path:   /logout