gs_user_user:
    resource: "@GSUserBundle/Resources/config/routes/user.yml"
    prefix: /user

gs_client_client:
    resource: "@GSUserBundle/Resources/config/routes/client.yml"
    prefix: /client

gs_zone_zone:
    resource: "@GSUserBundle/Resources/config/routes/zone.yml"
    prefix: /zone
    
gs_street_street:
    resource: "@GSUserBundle/Resources/config/routes/street.yml"
    prefix: /street
    
gs_claims_claims:
    resource: "@GSUserBundle/Resources/config/routes/claims.yml"
    prefix: /claims

gs_contract_contract:
    resource: "@GSUserBundle/Resources/config/routes/contract.yml"
    prefix: /contract
    
gs_counter_counter:
    resource: "@GSUserBundle/Resources/config/routes/counter.yml"
    prefix: /counter
        
gs_reading_reading:
    resource: "@GSUserBundle/Resources/config/routes/reading.yml"
    prefix: /reading

gs_incidence_incidence:
    resource: "@GSUserBundle/Resources/config/routes/incidence.yml"
    prefix: /incidence
    
gs_bill_bill:
    resource: "@GSUserBundle/Resources/config/routes/bill.yml"
    prefix: /bill
# Autentication

gs_user_homepage:
    path:   /
    defaults: { _controller: GSUserBundle:User:home }

gs_user_login:
    path:   /login
    defaults: { _controller: GSUserBundle:Security:login }

gs_user_login_check:
    path:   /login_check
    defaults: { _controller: GSUserBundle:User:loginCheck }
    
gs_user_logout:
    path:   /logout