<?php

namespace GS\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\EntityManager;

/**
 * BillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillRepository extends EntityRepository
{
    public function findByLetters($integer){
        return $this->getEntityManager()->createQuery('SELECT b FROM GSUserBundle:Bill b  
                WHERE b.id LIKE :integer')
                ->setParameter('integer','%'.$integer.'%')
                ->getResult();
    }
    
    public function findClient($string){
        return $this->getEntityManager()->createQuery('SELECT c FROM GSUserBundle:Client c 
                WHERE c.nombre LIKE :string')
                ->setParameter('string','%'.$string.'%')
                ->getResult();
    }
    
    public function findContract($integer, $id){
        return $this->getEntityManager()->createQuery('SELECT c FROM GSUserBundle:Contract c
                WHERE c.id LIKE :integer AND c.client= :id')
                ->setParameter('integer','%'.$integer.'%')
                ->setParameter('id', $id)
                ->getResult();
    }
    
    public function fillContract($id){
        return $this->getEntityManager()->createQuery('SELECT c FROM GSUserBundle:Contract c 
                WHERE c.client= :id')
                ->setParameter('id',$id)
                ->getResult();
    }
    
    public function findCounter($id){
        return $this->getEntityManager()->createQuery('SELECT c FROM GSUserBundle:Counter c 
                WHERE c.contract= :id AND c.fBaja IS NULL')
                ->setParameter('id',$id)
                ->getResult();
    }
    
    public function findReading($id){
        return $this->getEntityManager()->createQuery('SELECT r FROM GSUserBundle:Reading r 
                WHERE r.counter= :id')
                ->setParameter('id',$id)
                ->getResult();
    }
}
