<?php

namespace GS\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\EntityManager;

/**
 * BillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillRepository extends EntityRepository
{
    public function findByLetters($integer){
        return $this->getEntityManager()
        ->createQueryBuilder()
        ->select('b')
        ->from('GSUserBundle:Bill', 'b')
        ->innerJoin('b.contract','bc')
        ->where('bc.id LIKE :integer')
        ->setParameter('integer','%'.$integer.'%')
        ->getQuery()
        ->getResult();
    }
    
   
    public function fillContract($id){
        return $this->getEntityManager()->createQuery('SELECT c FROM GSUserBundle:Contract c 
                WHERE c.client= :id')
                ->setParameter('id',$id)
                ->getResult();
    }
    
    public function findCounter($id){
        return $this->getEntityManager()->createQuery('SELECT c FROM GSUserBundle:Counter c 
                WHERE c.contract= :id AND c.fBaja IS NULL')
                ->setParameter('id',$id)
                ->getResult();
    }
    
    public function findReading($id){
        return $this->getEntityManager()->createQuery('SELECT r FROM GSUserBundle:Reading r 
                WHERE r.counter= :id')
                ->setParameter('id',$id)
                ->getResult();
    }
    
    public function findByLettersContract($string){
        return $this->getEntityManager()
        ->createQueryBuilder()
        ->select('c')
        ->from('GSUserBundle:Contract', 'c')
        ->innerJoin('c.client','cc')
        ->where('cc.nombre LIKE :string OR cc.apellidos LIKE :string OR c.id LIKE :string')
        ->setParameter('string','%'.$string.'%')
        ->getQuery()
        ->getResult();
    }
    
}
