<?php

namespace GS\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClaimsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClaimsRepository extends EntityRepository
{
}
