<?php

namespace GS\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\EntityManager;


/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{
    public function findByLetters($string){
        return $this->getEntityManager()->createQuery('SELECT c FROM GSUserBundle:Client c  
                WHERE c.nombre LIKE :string OR c.apellidos LIKE :string')
                ->setParameter('string','%'.$string.'%')
                ->getResult();
    }
}
