<?php

namespace GS\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\EntityManager;

/**
 * ContractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractRepository extends EntityRepository
{
    public function findByLetters($integer){
        return $this->getEntityManager()->createQuery('SELECT c FROM GSUserBundle:Contract c  
                WHERE c.id LIKE :integer')
                ->setParameter('integer','%'.$integer.'%')
                ->getResult();
    }
}
