<?php

namespace GS\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\EntityManager;

/**
 * ContractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractRepository extends EntityRepository
{
    public function findByLetters($integer){
        return $this->getEntityManager()->createQuery('SELECT c FROM GSUserBundle:Contract c  
                WHERE c.id LIKE :integer')
                ->setParameter('integer','%'.$integer.'%')
                ->getResult();
    }
    
    public function findClient($string){
        return $this->getEntityManager()->createQuery('SELECT c FROM GSUserBundle:Client c 
                WHERE c.nombre LIKE :string')
                ->setParameter('string','%'.$string.'%')
                ->getResult();
    }
    
    public function findStreet($string){
        return $this->getEntityManager()->createQuery('SELECT s FROM GSUserBundle:Street s
                WHERE s.nombre LIKE :string')
                ->setParameter('string','%'.$string.'%')
                ->getResult();
    }
}
