<?php

namespace GS\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\EntityManager;

/**
 * CounterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CounterRepository extends EntityRepository
{
    public function findByLetters($integer){
        return $this->getEntityManager()->createQuery('SELECT c FROM GSUserBundle:Counter c  
                WHERE c.nContador LIKE :integer')
                ->setParameter('integer','%'.$integer.'%')
                ->getResult();
    }
}
