<?php

namespace GS\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CounterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CounterRepository extends EntityRepository
{
}
