<?php

namespace GS\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\EntityManager;

/**
 * IncidenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncidenceRepository extends EntityRepository
{
    public function findByLetters($string){
        return $this->getEntityManager()->createQuery('SELECT i FROM GSUserBundle:Incidence i  
                WHERE i.tipo LIKE :string')
                ->setParameter('string','%'.$string.'%')
                ->getResult();
    }
}
