<?php

namespace GS\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\EntityManager;

/**
 * ReadingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReadingRepository extends EntityRepository
{
    public function findByZone($string){
     return $this->getEntityManager()
        ->createQueryBuilder()
        ->select('c')
        ->from('GSUserBundle:Contract', 'c')
        ->innerJoin('c.street','cs')
        ->innerJoin('cs.zone','csz')
        ->where('csz.id = :zone_id AND c.activo=1')
        ->setParameter('zone_id', $string)
        ->getQuery()
        ->getResult();
    }
}
