<?php

namespace GS\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\EntityManager;

/**
 * StreetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StreetRepository extends EntityRepository
{
    public function findByLetters($string){
        return $this->getEntityManager()->createQuery('SELECT s FROM GSUserBundle:Street s  
                WHERE s.nombre LIKE :string')
                ->setParameter('string','%'.$string.'%')
                ->getResult();
    }
    
    public function findZone($string){
        return $this->getEntityManager()->createQuery('SELECT z FROM GSUserBundle:Zone z  
                WHERE z.nombre LIKE :string')
                ->setParameter('string','%'.$string.'%')
                ->getResult();
    }
    
}
